australia_and_oceania:
  name: "Australia / Oceania"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/australia-and-oceania"
  start_times:
    - "08:00 Australian Western Standard Time"
    - "11:00 Australian Eastern Daylight Time"
    - "13:00 New Zealand Daylight Time"
  end_times:
    - "14:00 Australian Western Standard Time"
    - "17:00 Australian Eastern Daylight Time"
    - "19:00 New Zealand Daylight Time"

  lead:
    name: "Amy Kapernick"
    pronouns: "(She/Her)"
    profile_picture: "https://on.notist.cloud/profile/pr-amyskapers-large-5b47451882f976c0.jpg"
    twitter: "Amys_Kapers"
    message: ""
    bio: "Amy is a freelance developer, who spends her time volunteering at various community events in Perth, works as an evangelist for YOW! and is a Twilio Champion and Microsoft MVP. In her spare time she blogs about tech, the web and life and speaks at various conferences all over the world."
  speakers:
  - name: "Sonia Cuff"
    pronouns: "(She/Her)"
    profile_picture: "https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F22191da2-f3a1-46a5-9cd6-48f0ad9a5f03%2FSoniaCuff_HIGHRES_Colour_DarkBack_Crop.jpg?table=block&id=aae41a31-cac8-4903-a28f-8dfd91913190&width=600&userId=&cache=v2"
    twitter: "SoniaCuff"
    talk_title: "An audience of One – Skills for speaking to camera"
  - name: "Leila Etaati"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1150542359525875712/gVuD7ILt_400x400.png"
    twitter: "leila_etaati"
    talk_title: "Panel: Presenting as an ESL Speaker"
  - name: "Melissa Houghton"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1303213533639843841/LW1K_3Ik_400x400.jpg"
    twitter: "meliss_houghton"
    talk_title: "Panel: How to get in to conference speaking"
  - name: "Rebecca Jackson"
    pronouns: "(She/Her/They)"
    profile_picture: "https://pbs.twimg.com/profile_images/1222632216963899392/R6TXpcLw_400x400.jpg"
    twitter: "_rebeccajackson"
    talk_title: "Personalise your PowerPoint presentation with your own Sketches"
  - name: "Larene Le Gassick"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/955384570731413504/ZFHTOLvV_400x400.jpg"
    twitter: "LareneLg"
    talk_title: "Panel: What Makes a Good Talk Abstract"
  - name: "Akanksha Malik"
    pronouns: "(She/Her)"
    profile_picture: "https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F52265065-eafd-46d4-8ba2-c7a5a904fce7%2FAkanksha_Malik.jpeg?table=block&id=32bb932a-067e-43f3-a695-b6d36c0024e6&width=600&userId=&cache=v2"
    twitter: "akankshamalik96"
    talk_title: "Panel: How to get in to conference speaking"
  - name: "Michele Playfair"
    pronouns: "(She/Her)"
    profile_picture: "https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3fa4f271-b90f-44e1-951f-3e305aef0157%2F44528974930_e3a328cd02_o20(2).jpg?table=block&id=1c85756f-2e24-4a68-8b60-41d5ebebe4c2&width=600&userId=&cache=v2"
    twitter: "micheleplayfair"
    talk_title: "Death by Powerpoint"
  - name: "Allison Ravenhall"
    pronouns: "(She/Her)"
    profile_picture: "/images/Allison_Ravenhall.png"
    twitter: "RavenAlly"
    talk_title: "How to present inclusively"
  - name: "Michelle Sandford"
    pronouns: "(She/Her)"
    profile_picture: "https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F6a7c3c05-541f-4fce-b0ee-5973e837b6ef%2F1562105921925.jpg?table=block&id=d87b265d-9e6f-4c88-80b2-c961bfe658f7&width=600&userId=&cache=v2"
    twitter: "msandfor"
    talk_title: "Panel: So Now You're a Conference Speaker"
  - name: "Rabia Williams"
    pronouns: "(She/Her)"
    profile_picture: "https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F806d4fe1-0801-44fc-bbc8-f3dfd6b47223%2Fprofile.jpg?table=block&id=6a57a5a6-2816-4736-9c88-302e2c563f80&width=600&userId=&cache=v2"
    twitter: "williamsrabia"
    talk_title: "Panel: How to get in to conference speaking"
  - name: "Katrina Clokie"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/585624785302003713/IwRMMxVR_400x400.jpg"
    twitter: "katrinaclokie"
    talk_title: "Panel: What Makes a Good Talk Abstract"
  - name: "Wagner Silveira"
    pronouns: "(He/Him)"
    profile_picture: "https://pbs.twimg.com/profile_images/873012448789282816/3PT5HR91_400x400.jpg"
    twitter: "wsilveiranz"
    talk_title: "Panel: Presenting as an ESL Speaker"
  - name: "Sandy Mamoli"
    pronouns: ""
    profile_picture: "https://pbs.twimg.com/profile_images/891795587036700672/km-tFgSY_400x400.jpg"
    twitter: "smamol"
    talk_title: "Panel: So Now You're a Conference Speaker"
  - name: "Nelly Sattari"
    pronouns: "She/Her"
    profile_picture: "https://pbs.twimg.com/profile_images/1282137150478143488/tz95_pRf_400x400.jpg"
    twitter: "nelly_sattari"
    talk_title: ""


asia:
  name: "Asia"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/asia"
  start_times:
    - "09:30 India Standard Time"
    - "12:00 Singapore Standard Time"
    - "13:00 Japan Standard Time"
  end_times:
    - "15:30 India Standard Time"
    - "18:00 Singapore Standard Time"
    - "19:00 Japan Standard Time"

  lead:
    name: "HJ Chen"
    profile_picture: "https://pbs.twimg.com/profile_images/1138414735500595200/MfOU2-0K_400x400.png"
    twitter: "hj_chen"
    message: ""
    bio: "Chen Hui Jing is a self-taught designer and developer with an inordinate love for CSS. Reducing lines of code in her web projects makes her extremely happy. She used to play basketball full-time and launched her web career during downtime between training sessions. Hui Jing is currently a web developer at Shopify."
  speakers:
  - name: "Shawn Wang"
    pronouns: "(He/Him)"
    profile_picture: "https://avatars3.githubusercontent.com/u/6764957?s=460&v=4"
    twitter: "swyx"
    talk_title: "Prerecording Talks for Online Conferences"
  - name: "Seo Jiyeon"
    pronouns: "(She/Her)"
    profile_picture: "https://i.imgur.com/nfZBZQW.jpg"
    twitter: "seojeee"
    talk_title: "Quick start! for tech talk beginners"
  - name: "Tan Li Hau"
    pronouns: "(He/Him)"
    profile_picture: "https://pbs.twimg.com/profile_images/1100040104754610178/kSgYjCmM_400x400.png"
    twitter: "lihautan"
    talk_title: "My New Year Resolution - Speak at a conference"

africa:
  name: "Africa"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/africa"
  start_times:
    - "09:00 Greenwich Mean Time"
    - "12:00 East Africa Time"
  end_times:
    - "15:00 Greenwich Mean Time"
    - "18:00 East Africa Time"

  lead:
    name: "Oliver Mensah"
    profile_picture: "https://pbs.twimg.com/profile_images/1237246752283078657/K960GN4m_400x400.jpg"
    twitter: "OliverMensahDev"
    pronouns: "(He/Him)"
    message: "Hey there!
    <br>
    I can't wait to welcome you all to CFP Day 2021"
    bio: "Oliver is a Software Engineer who currently specializes in creating resilient web services. He has a working understanding of modern software engineering and always looking for better principles and practices to design software.
Apart from his professional career, Oliver actively participates in the development of the Ghana Developer Ecosystem."

  speakers:
  - name: "Lebogang Madise"
    pronouns: "(She/Her)"
    profile_picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-a0uuJ8izRJJAYG1zkI1p36hrqLHJbI6VUQ&usqp=CAU"
    twitter: "LeboMadise"
    talk_title: "i = imposter_syndrome, u = real;"
  - name: "Peter Mbanugo"
    pronouns: "(He/Him)"
    profile_picture: "https://pbs.twimg.com/profile_images/1104395843711451137/xAwVJnBg_400x400.png"
    twitter: "p_mbanugo"
    talk_title: "Picking a talk topic"
  - name: "Faith Mpara"
    pronouns: "(She/Her)"
    profile_picture: "/images/Mpara_Faith.png"
    twitter: "mpara10"
    talk_title: "Caring for your Audience"
  - name: "Lawrence Muthoga"
    pronouns: "(He/Him)"
    profile_picture: "https://pbs.twimg.com/profile_images/1290585109515599872/q2e0gKAZ_400x400.png"
    twitter: "larrygify"
    talk_title: " Structuring your talk and Slide design"
  producers:
  - name: "Botsyoe Edinam Lily"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1331218834641080327/0OBUbTOi_400x400.jpg"
    twitter: "Edinam233"



europe:
  name: "Europe"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/europe"
  start_times:
    - "09:00 Greenwich Mean Time"
    - "10:00 Central European Time"
    - "12:00 Moscow Time"
  end_times:
    - "15:00 Greenwich Mean Time"
    - "16:00 Central European Time"
    - "18:00 Moscow Time"

  lead:
    name: "Suze Shardlow"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1160159491364704256/AVZpDOSg_400x400.jpg"
    twitter: "SuzeShardlow"
    message: "Hi!  Whether you're trying to find a topic for your next tech talk, or want to submit your first conference talk proposal, we've got actionable advice for you.  I look forward to welcoming you to the first online Global Diversity CFP Day on Saturday 23rd January 2021!"
    bio: "Suze Shardlow is a software engineer, coding instructor, event MC and writer who has spoken at tech conferences and meetups in several countries.  She loves crafting and running and is currently trying to improve her 5k and 10k times."


north_america:
  name: "North America"
  # start_time: "11am (ET)"
  # end_time: "5pm (ET)"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/north-america"
  start_times:
    - "07:00 Hawaii-Aleutian Standard Time"
    - "09:00 Pacific Standard Time"
    - "12:00 Eastern Standard Time"
  end_times:
    - "13:00 Hawaii-Aleutian Standard Time"
    - "15:00 Pacific Standard Time"
    - "18:00 Eastern Standard Time"

  lead:
    name: "Aisha Blake"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1312184097062694912/ZBYeYZzI_400x400.jpg"
    twitter: "AishaBlake"
    message: "Hi!! I've loved seeing new speakers take the stage after participating in CFP Day. I can't wait to hear what you have to say!"
    bio: "Aisha is a champion of feedback, a fierce accessibility advocate, and a steward of strong teams. She's the creator of <a href='https://www.titleofconf.org/'>&lt;title of conf&gt;</a>, a musical tech conference. She also co-organizes <a href='https://selfconference.org/''>self.conference</a> and <a href='https://twitter.com/SpeakersInTech'>Detroit Speakers in Tech</a>. A theatre kid turned tech community leader, she uses speaking and teaching to help others shine as brightly as they can. In her spare time, Aisha sings karaoke and pets dogs."
  # hosts:
  # - name: "Henri Helvetica"
  #   profile_picture: "https://pbs.twimg.com/profile_images/960605708202004481/MMNCgNgM_400x400.jpg"
  #   twitter: "HenriHelvetica"
  #   message: ""
  #   bio: ""
  # - name: "Raquel Vélez"
  #   profile_picture: "https://pbs.twimg.com/profile_images/1270728520394665985/IG37--2e_400x400.jpg"
  #   twitter: "rockbot"
  #   message: ""
  #   bio: ""
  speakers:
  - name: "Laurie Barth"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1334855286213980162/HdoG7aht_400x400.jpg"
    twitter: "laurieontech"
    talk_title: "CFP Advice & Finding a Topic"
  - name: "Henri Helvetica"
    profile_picture: "/images/Henri_Helvetica.jpg"
    twitter: "HenriHelvetica"
    pronouns: "(He/Him)"
    talk_title: "CFP Advice"
  - name: "Ben Hong"
    profile_picture: "https://pbs.twimg.com/profile_images/1305674805757333504/-4nFHMCK_400x400.jpg"
    twitter: "bencodezen"
    pronouns: "(He/Him)"
    talk_title: "CFP Advice & How to Prepare"
  - name: "Ariba Jahan"
    profile_picture: "/images/Ariba_Jahan.jpg"
    twitter: "aribajahan"
    pronouns: "(She/Her)"
    talk_title: "CFP Advice"
  - name: "Angie Jones"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1319649316965736451/-XOCbnFu_400x400.jpg"
    twitter: "techgirl1908"
    talk_title: "How to Secure Speaking Engagements"
  - name: "Tatiana Mac"
    pronouns: "(She/They/Hän)"
    profile_picture: "https://pbs.twimg.com/profile_images/1329703467124813825/K8VnCIn9_400x400.jpg"
    twitter: "TatianaTMac"
    talk_title: "Caring for Your Audience"
  - name: "EJ Mason"
    pronouns: "(they/them/theirs)"
    profile_picture: "https://pbs.twimg.com/profile_images/1218293785748099072/aEABOOXN_400x400.jpg"
    twitter: "codeability"
    talk_title: "Caring for Your Audience"
  - name: "Diana Rodriguez"
    pronouns: "(She/Her)"
    profile_picture: ""
    twitter: "cotufa8"
    talk_title: "Structuring a Talk"
  - name: "T Sripunvoraskul"
    pronouns: "(They/Them)"
    profile_picture: "/images/t.png"
    twitter: "tsripunv"
    talk_title: "Slide Design"
  - name: "Carina C. Zona"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/3448372624/fbfdda29ff5fcee3ff0ad60e2d3932ae_400x400.jpeg"
    twitter: "cczona"
    talk_title: "You The Keynoter"
  producers:
  - name: "Kurt Kemple"
    pronouns: "(He/Him)"
    profile_picture: "/images/Kurt.png"
    twitter: "theworstdev"


    # moderators:
    # - name: "Henri Helvetica"
    #   profile_picture: "https://pbs.twimg.com/profile_images/960605708202004481/MMNCgNgM_400x400.jpg"
    #   twitter: "HenriHelvetica"
    #   message: ""
    #   bio: ""
    # - name: "Raquel Vélez"
    #   profile_picture: "https://pbs.twimg.com/profile_images/1270728520394665985/IG37--2e_400x400.jpg"
    #   twitter: "rockbot"
    #   message: ""
    #   bio: ""


south_america:
  name: "South America"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/south-america"
  start_times:
    - "10:00 Peru Standard Time"
    - "11:00 Bolivia Time"
    - "12:00 Argentina Standard Time"
  end_times:
    - "16:00 Peru Standard Time"
    - "17:00 Bolivia Time"
    - "18:00 Argentina Standard Time"


  lead:
    name: "Elizabeth Portilla"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1245182655144001538/Pm5Pzb5C_400x400.jpg"
    twitter: "lizita136"
    message: ""
    bio: ""

  speakers:
  - name: "Leonidas Esteban"
    pronouns: "(He/his)"
    profile_picture: "https://pbs.twimg.com/profile_images/1324801908851298314/IAhTiaPE_400x400.jpg"
    twitter: "@LeonidasEsteban"
    talk_title: "How to Secure Speaking Engagements "
  - name: "Mike Nieva"
    pronouns: "(He/his)"
    profile_picture: "https://pbs.twimg.com/profile_images/867559664321536001/C5x7xxHg_400x400.jpg"
    twitter: "@mikenieva"
    talk_title: "Caring for Your Audience"
  - name: "Paulina Treviño"
    pronouns: "(She/her)"
    profile_picture: ""
    twitter: "@mebrainstorming"
    talk_title: "Working Through Anxiety"
  - name: "Lesly Zerna"
    pronouns: "(She/her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1090257515529396224/VJw5P_DI_400x400.jpg"
    twitter: "@leslysandra"
    talk_title: "CFP Advice & How to Prepare"


