australia_and_oceania:
  name: "Australia / Oceania"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/australia-and-oceania"
  start_times:
    - "08:00 Australian Western Standard Time"
    - "11:00 Australian Eastern Daylight Time"
    - "13:00 New Zealand Daylight Time"
  end_times:
    - "14:00 Australian Western Standard Time"
    - "17:00 Australian Eastern Daylight Time"
    - "19:00 New Zealand Daylight Time"

  lead:
    name: "Amy Kapernick"
    pronouns: "(She/Her)"
    profile_picture: "https://on.notist.cloud/profile/pr-amyskapers-large-5b47451882f976c0.jpg"
    twitter: "Amys_Kapers"
    message: ""
    bio: "Amy is a freelance developer, who spends her time volunteering at various community events in Perth, works as an evangelist for YOW! and is a Twilio Champion and Microsoft MVP. In her spare time she blogs about tech, the web and life and speaks at various conferences all over the world."


asia:
  name: "Asia"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/asia"
  start_times:
    - "09:30 India Standard Time"
    - "12:00 Singapore Standard Time"
    - "13:00 Japan Standard Time"
  end_times:
    - "15:30 India Standard Time"
    - "18:00 Singapore Standard Time"
    - "19:00 Japan Standard Time"

  lead:
    name: "HJ Chen"
    profile_picture: "https://pbs.twimg.com/profile_images/1138414735500595200/MfOU2-0K_400x400.png"
    twitter: "hj_chen"
    message: ""
    bio: ""


africa:
  name: "Africa"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/africa"
  start_times:
    - "09:00 Greenwich Mean Time"
    - "12:00 East Africa Time"
  end_times:
    - "15:00 Greenwich Mean Time"
    - "18:00 East Africa Time"

  lead:
    name: "Oliver Mensah"
    profile_picture: "https://pbs.twimg.com/profile_images/1237246752283078657/K960GN4m_400x400.jpg"
    twitter: "OliverMensahDev"
    message: "Hey there!
    <br>
    I can't wait to welcome you all to CFP Day 2021"
    bio: "Oliver is a Software Engineer who currently specializes in creating resilient web services. He has a working understanding of modern software engineering and always looking for better principles and practices to design software.
Apart from his professional career, Oliver actively participates in the development of the Ghana Developer Ecosystem."


europe:
  name: "Europe"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/europe"
  start_times:
    - "09:00 Greenwich Mean Time"
    - "10:00 Central European Time"
    - "12:00 Moscow Time"
  end_times:
    - "15:00 Greenwich Mean Time"
    - "16:00 Central European Time"
    - "18:00 Moscow Time"

  lead:
    name: "Suze Shardlow"
    profile_picture: "https://pbs.twimg.com/profile_images/1160159491364704256/AVZpDOSg_400x400.jpg"
    twitter: "SuzeShardlow"
    message: ""
    bio: ""



north_america:
  name: "North America"
  # start_time: "11am (ET)"
  # end_time: "5pm (ET)"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/north-america"
  start_times:
    - "07:00 Hawaii-Aleutian Standard Time"
    - "09:00 Pacific Standard Time"
    - "12:00 Eastern Standard Time"
  end_times:
    - "13:00 Hawaii-Aleutian Standard Time"
    - "15:00 Pacific Standard Time"
    - "18:00 Eastern Standard Time"

  lead:
    name: "Aisha Blake"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1312184097062694912/ZBYeYZzI_400x400.jpg"
    twitter: "AishaBlake"
    message: "Hi!! I've loved seeing new speakers take the stage after participating in CFP Day. I can't wait to hear what you have to say!"
    bio: "Aisha is a champion of feedback, a fierce accessibility advocate, and a steward of strong teams. She's the creator of <a href='https://www.titleofconf.org/'>&lt;title of conf&gt;</a>, a musical tech conference. She also co-organizes <a href='https://selfconference.org/''>self.conference</a> and <a href='https://twitter.com/SpeakersInTech'>Detroit Speakers in Tech</a>. A theatre kid turned tech community leader, she uses speaking and teaching to help others shine as brightly as they can. In her spare time, Aisha sings karaoke and pets dogs."
  # hosts:
  # - name: "Henri Helvetica"
  #   profile_picture: "https://pbs.twimg.com/profile_images/960605708202004481/MMNCgNgM_400x400.jpg"
  #   twitter: "HenriHelvetica"
  #   message: ""
  #   bio: ""
  # - name: "Raquel Vélez"
  #   profile_picture: "https://pbs.twimg.com/profile_images/1270728520394665985/IG37--2e_400x400.jpg"
  #   twitter: "rockbot"
  #   message: ""
  #   bio: ""
  speakers:
  - name: "Laurie Barth"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1334855286213980162/HdoG7aht_400x400.jpg"
    twitter: "laurieontech"
    talk_title: "CFP Advice & Finding a Topic"
  - name: "Henri Helvetica"
    profile_picture: "https://pbs.twimg.com/profile_images/960605708202004481/MMNCgNgM_400x400.jpg"
    twitter: "HenriHelvetica"
    talk_title: "CFP Advice"
  - name: "Ben Hong"
    profile_picture: "https://pbs.twimg.com/profile_images/1305674805757333504/-4nFHMCK_400x400.jpg"
    twitter: "bencodezen"
    talk_title: "CFP Advice & How to Prepare"
  - name: "Angie Jones"
    profile_picture: "https://pbs.twimg.com/profile_images/1319649316965736451/-XOCbnFu_400x400.jpg"
    twitter: "techgirl1908"
    talk_title: "How to Secure Speaking Engagements"
  - name: "Tatiana Mac"
    pronouns: "(She/They/Hän)"
    profile_picture: "https://pbs.twimg.com/profile_images/1329703467124813825/K8VnCIn9_400x400.jpg"
    twitter: "TatianaTMac"
    talk_title: "Caring for Your Audience"
  - name: "EJ Mason"
    profile_picture: ""
    twitter: ""
    talk_title: "Caring for Your Audience"
  - name: "Diana Rodriguez"
    pronouns: "(She/Her)"
    profile_picture: ""
    twitter: "cotufa8"
    talk_title: "Structuring a Talk"
  - name: "Amberley Romo"
    profile_picture: ""
    twitter: ""
    talk_title: "Working Through Anxiety"
  - name: "T Sripunvoraskul"
    pronouns: "(They/Them)"
    profile_picture: "https://pbs.twimg.com/profile_images/1156448121657819136/zNTOu7gf_400x400.jpg"
    twitter: "tsripunv"
    talk_title: "Slide Design"
  - name: "Carina C. Zona"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/3448372624/fbfdda29ff5fcee3ff0ad60e2d3932ae_400x400.jpeg"
    twitter: "cczona"
    talk_title: "Keynote"
    # moderators:
    # - name: "Henri Helvetica"
    #   profile_picture: "https://pbs.twimg.com/profile_images/960605708202004481/MMNCgNgM_400x400.jpg"
    #   twitter: "HenriHelvetica"
    #   message: ""
    #   bio: ""
    # - name: "Raquel Vélez"
    #   profile_picture: "https://pbs.twimg.com/profile_images/1270728520394665985/IG37--2e_400x400.jpg"
    #   twitter: "rockbot"
    #   message: ""
    #   bio: ""


south_america:
  name: "South America"
  ticketing_url: "https://ti.to/global-diversity-cfp-day-2021/south-america"
  start_times:
    - "10:00 Peru Standard Time"
    - "11:00 Bolivia Time"
    - "12:00 Argentina Standard Time"
  end_times:
    - "16:00 Peru Standard Time"
    - "17:00 Bolivia Time"
    - "18:00 Argentina Standard Time"


  lead:
    name: "Elizabeth Portilla"
    pronouns: "(She/Her)"
    profile_picture: "https://pbs.twimg.com/profile_images/1245182655144001538/Pm5Pzb5C_400x400.jpg"
    twitter: "lizita136"
    message: ""
    bio: ""
